SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE OS1
WHERE 1 < (SELECT COUNT(*) FROM ONLINE_SALE OS2 WHERE OS1.USER_ID = OS2.USER_ID AND OS1.PRODUCT_ID = OS2.PRODUCT_ID)
ORDER BY USER_ID ASC, PRODUCT_ID DESC;