SELECT C.CAR_ID, 
       C.CAR_TYPE, 
       FLOOR(C.DAILY_FEE * (1.0 - NVL(P.DISCOUNT_RATE, 0) / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
       ON P.CAR_TYPE = C.CAR_TYPE 
       AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221130'
        AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221101'
  )
  AND FLOOR(C.DAILY_FEE * (1.0 - NVL(P.DISCOUNT_RATE, 0) / 100) * 30) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
