SELECT O.PRODUCT_ID, P.PRODUCT_NAME, (O.TOTAL_AMOUNT*P.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') = '202205'
    GROUP BY PRODUCT_ID
) O
INNER JOIN FOOD_PRODUCT P
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC

