SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_ORDER
FROM (
SELECT FLAVOR, TOTAL_ORDER
FROM FIRST_HALF
UNION
SELECT FLAVOR, TOTAL_ORDER
FROM JULY)
GROUP BY FLAVOR
ORDER BY SUM_ORDER DESC)
FETCH FIRST 3 ROWS ONLY