SELECT YEAR(E1.DIFFERENTIATION_DATE) YEAR, (E2.MAX_SIZE-E1.SIZE_OF_COLONY) YEAR_DEV, E1.ID
FROM ECOLI_DATA E1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) E2
ON YEAR(E1.DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC