#세대를 표시하는 쿼리
WITH RECURSIVE GENERATE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT o.ID, o.PARENT_ID, p.GENERATION+1 AS GENERATION
    FROM ECOLI_DATA o
    JOIN GENERATE p
    ON o.PARENT_ID = p.ID
)

# SELECT *
# FROM GENERATE
# ORDER BY GENERATION ASC

SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM GENERATE
WHERE ID NOT IN(SELECT PARENT_ID FROM GENERATE WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION