SELECT ID, CASE
WHEN rowNum <= TOTALCOUNT/4 THEN 'CRITICAL'
WHEN rowNum <= TOTALCOUNT/2 THEN 'HIGH'
WHEN rowNum <= TOTALCOUNT*3/4 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, 
    ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS rowNum, 
    (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTALCOUNT 
    FROM ECOLI_DATA
) AS a
ORDER BY ID ASC