SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, (SELECT CODE
FROM SKILLCODES
WHERE NAME = 'Python') S1, (SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#') S2
WHERE D.SKILL_CODE & S1.CODE = S1.CODE OR D.SKILL_CODE & S2.CODE = S2.CODE
ORDER BY D.ID

# SELECT CODE
# FROM SKILLCODES
# WHERE NAME = 'Python'

# SELECT CODE
# FROM SKILLCODES
# WHERE NAME = 'C#'