SELECT I1.ID, N.FISH_NAME, I1.LENGTH
FROM FISH_INFO I1
LEFT JOIN FISH_NAME_INFO N
ON I1.FISH_TYPE = N.FISH_TYPE
WHERE I1.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO I2 WHERE I2.FISH_TYPE = I1.FISH_TYPE)
ORDER BY I1.ID ASC