# 2 세대 찾는 쿼리
# SELECT o.ID, o.PARENT_ID
# FROM ECOLI_DATA o
# LEFT JOIN (SELECT ID, PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL) AS p
# ON o.PARENT_ID = p.ID
# ORDER BY ID ASC

# 3세대 찾는 쿼리
SELECT o2.ID
FROM ECOLI_DATA o2
JOIN (
    SELECT o.ID, o.PARENT_ID 
    FROM ECOLI_DATA o
    JOIN (
        SELECT ID, PARENT_ID 
        FROM ECOLI_DATA 
        WHERE PARENT_ID IS NULL
    ) AS p
    ON o.PARENT_ID = p.ID
    ORDER BY o.ID ASC
) AS t
ON o2.PARENT_ID = t.ID
ORDER BY o2.ID ASC